{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue255;\red255\green255\blue254;\red0\green0\blue0;
\red144\green1\blue18;\red19\green118\blue70;\red14\green110\blue109;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c100000;\cssrgb\c100000\c100000\c99608;\cssrgb\c0\c0\c0;
\cssrgb\c63922\c8235\c8235;\cssrgb\c3529\c52549\c34510;\cssrgb\c0\c50196\c50196;}
\margl1440\margr1440\vieww27940\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 let\cf0 \cb1 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf0 \cb3   Source = Xml.Tables(Web.Contents(\cf5 \strokec5 "https://data.cityofnewyork.us/download/qb3k-n8mm/application%2Fxml"\cf0 \strokec4 )),\cb1 \
\cb3   Navigation = Source\{\cf6 \strokec6 3\cf0 \strokec4 \}[Table],\cb1 \
\cb3   #"Navigation 1" = Navigation\{\cf6 \strokec6 0\cf0 \strokec4 \}[Table],\cb1 \
\cb3   #"Navigation 2" = #"Navigation 1"\{\cf6 \strokec6 0\cf0 \strokec4 \}[Row],\cb1 \
\cb3   #"Expanded Cell" = Table.ExpandTableColumn(#"Navigation 2", \cf5 \strokec5 "Cell"\cf0 \strokec4 , \{\cf5 \strokec5 "Data"\cf0 \strokec4 , \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet"\cf0 \strokec4 , \cf5 \strokec5 "NamedCell"\cf0 \strokec4 \}, \{\cf5 \strokec5 "Data"\cf0 \strokec4 , \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet.1"\cf0 \strokec4 , \cf5 \strokec5 "NamedCell"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Expanded Data" = Table.ExpandTableColumn(#"Expanded Cell", \cf5 \strokec5 "Data"\cf0 \strokec4 , \{\cf5 \strokec5 "Element:Text"\cf0 \strokec4 , \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet"\cf0 \strokec4 \}, \{\cf5 \strokec5 "Element:Text"\cf0 \strokec4 , \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet.2"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Expanded urn:schemas-microsoft-com:office:spreadsheet.2" = Table.ExpandTableColumn(#"Expanded Data", \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet.2"\cf0 \strokec4 , \{\cf5 \strokec5 "Attribute:Type"\cf0 \strokec4 \}, \{\cf5 \strokec5 "Attribute:Type"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Removed columns" = Table.RemoveColumns(#"Expanded urn:schemas-microsoft-com:office:spreadsheet.2", \{\cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet.1"\cf0 \strokec4 , \cf5 \strokec5 "NamedCell"\cf0 \strokec4 , \cf5 \strokec5 "Attribute:Type"\cf0 \strokec4 , \cf5 \strokec5 "urn:schemas-microsoft-com:office:spreadsheet"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Removed top rows" = Table.Skip(#"Removed columns", \cf6 \strokec6 22\cf0 \strokec4 ),\cb1 \
\cb3   #"Replaced value" = Table.ReplaceValue(#"Removed top rows", \cf7 \strokec7 null\cf0 \strokec4 , \cf5 \strokec5 "N/A"\cf0 \strokec4 , Replacer.ReplaceValue, \{\cf5 \strokec5 "Element:Text"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Unpivoted columns" = Table.UnpivotOtherColumns(#"Replaced value", \{\}, \cf5 \strokec5 "Attribute"\cf0 \strokec4 , \cf5 \strokec5 "Value"\cf0 \strokec4 ),\cb1 \
\cb3   #"Added index" = Table.AddIndexColumn(#"Unpivoted columns", \cf5 \strokec5 "Index"\cf0 \strokec4 , \cf6 \strokec6 0\cf0 \strokec4 , \cf6 \strokec6 1\cf0 \strokec4 , Int64.Type),\cb1 \
\cb3   #"Inserted modulo" = Table.AddColumn(#"Added index", \cf5 \strokec5 "Modulo"\cf0 \strokec4 , \cf2 \strokec2 each\cf0 \strokec4  Number.Mod([Index], \cf6 \strokec6 22\cf0 \strokec4 ), Int64.Type),\cb1 \
\cb3   #"Removed columns 1" = Table.RemoveColumns(#"Inserted modulo", \{\cf5 \strokec5 "Attribute"\cf0 \strokec4 , \cf5 \strokec5 "Index"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Grouped rows" = Table.Group(#"Removed columns 1", \{\cf5 \strokec5 "Modulo"\cf0 \strokec4 \}, \{\{\cf5 \strokec5 "Count"\cf0 \strokec4 , \cf2 \strokec2 each\cf0 \strokec4  _, \cf2 \strokec2 type\cf0 \strokec4  nullable \cf7 \strokec7 table\cf0 \strokec4 [Value = \cf7 \strokec7 any\cf0 \strokec4 , Modulo = Int64.Type]\}\}),\cb1 \
\cb3   #"Added custom" = Table.AddColumn(#"Grouped rows", \cf5 \strokec5 "Custom"\cf0 \strokec4 , \cf2 \strokec2 each\cf0 \strokec4  Table.AddIndexColumn([Count], \cf5 \strokec5 "Index"\cf0 \strokec4 , \cf6 \strokec6 1\cf0 \strokec4 )),\cb1 \
\cb3   #"Expanded Custom" = Table.ExpandTableColumn(#"Added custom", \cf5 \strokec5 "Custom"\cf0 \strokec4 , \{\cf5 \strokec5 "Value"\cf0 \strokec4 , \cf5 \strokec5 "Index"\cf0 \strokec4 \}, \{\cf5 \strokec5 "Value"\cf0 \strokec4 , \cf5 \strokec5 "Index"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Removed columns 2" = Table.RemoveColumns(#"Expanded Custom", \{\cf5 \strokec5 "Count"\cf0 \strokec4 \}),\cb1 \
\cb3   #"Pivoted column" = Table.Pivot(Table.TransformColumnTypes(#"Removed columns 2", \{\{\cf5 \strokec5 "Modulo"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}\}), List.Distinct(Table.TransformColumnTypes(#"Removed columns 2", \{\{\cf5 \strokec5 "Modulo"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}\})[Modulo]), \cf5 \strokec5 "Modulo"\cf0 \strokec4 , \cf5 \strokec5 "Value"\cf0 \strokec4 ),\cb1 \
\cb3   #"Promoted headers" = Table.PromoteHeaders(#"Pivoted column", [PromoteAllScalars = \cf2 \strokec2 true\cf0 \strokec4 ]),\cb1 \
\cb3   #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", \{\{\cf5 \strokec5 "1"\cf0 \strokec4 , Int64.Type\}, \{\cf5 \strokec5 "Film"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Year"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "URL Encoded name"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Image File Name"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Agency Credit"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Artist Credit"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Director/Filmmaker Name"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Director/Filmmaker IMDB Link"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Location Display Text"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "LATITUDE"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 number\cf0 \strokec4 \}, \{\cf5 \strokec5 "LONGITUDE"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 number\cf0 \strokec4 \}, \{\cf5 \strokec5 "Borough"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Neighborhood"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Scene Type"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Media"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "IMDB LINK"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Client or book location indicator"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Notes"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Book Image"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Book Page"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "Display?"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}, \{\cf5 \strokec5 "IMAGE OF LOCATION"\cf0 \strokec4 , \cf2 \strokec2 type\cf0 \strokec4  \cf7 \strokec7 text\cf0 \strokec4 \}\})\cb1 \
\pard\pardeftab720\partightenfactor0
\cf2 \cb3 \strokec2 in\cf0 \cb1 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf0 \cb3   #"Changed column type"\cb1 \
}